apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-backend
  namespace: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanager-backend
  template:
    metadata:
      labels:
        app: taskmanager-backend
    spec:
      containers:
      - name: taskmanager-backend
        image: taskmanager-backend-image
        imagePullPolicy: Never  
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_NAME
          value: "taskManagerDB"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        ports:
        - containerPort: 8000