# Generated by Django 5.0.6 on 2024-05-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0003_alter_task_description_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
