# Generated by Django 5.0.6 on 2024-05-19 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0004_alter_task_description_alter_task_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-priority', '-due_date', 'progress')},
        ),
    ]
