# Generated by Django 5.0.6 on 2024-05-20 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0008_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], default=1),
        ),
    ]
